name: Download and Upload Spotify APKs to 123Pan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # 每天 01:00 UTC 执行（可自定义时间）

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run downloader
      env:
        PAN_COOKIE: ${{ secrets.PAN_COOKIE }}  # 从 Secrets 获取 cookie
      run: |
        python test.py
