name: Auto Download Spotify APKs

on:
  workflow_dispatch:  # 允许手动触发
  schedule:
    - cron: "0 1 * * *"  # 每天 01:00 UTC 执行，可改为你想要的时间

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: 拉取仓库
      uses: actions/checkout@v3

    - name: 设置 Python 环境
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: 安装依赖
      run: |
        pip install -r requirements.txt

    - name: 执行下载脚本
      run: |
        python spotify_downloader.py

    - name: 提交 APK 到仓库（可选）
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git add spotify_apks/
        git commit -m "auto: 下载 Spotify APK 文件" || echo "无更新"
        git push
